version: '3.5'

services:
  #################################################
  # Nginx
  #################################################
  nginx:
    image: nginx:latest
    build:
      context: docker/nginx
    container_name: nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/log:/var/log/nginx
      - ./html:/var/www/html
    ports:
      - 7888:80
      - 443:443
    depends_on:
      - php

  #################################################
  # PHP
  #################################################

  php:
    build:
      context: docker/php
      dockerfile: dockerfile
    container_name: php
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./html:/var/www/html

  #################################################
  # MySQL
  #################################################

  mysql:
    image: mysql:latest
    container_name: newmysql
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./docker/mysql/data:/var/lib/mysql             
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pf_project
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    ports:
      - 8888:80

  #################################################
  # PhpMyAdmin
  #################################################
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pf_project
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - 8889:80
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions
